previewsEnabled: true
previewsExpireAfterDays: 1
services:
- type: web
  name: my-web-app
  runtime: static
  buildCommand: npm run build
  staticPublishPath: build
  rootDir: my-web-app
- type: web
  name: react-app
  runtime: static
  buildCommand: npm run build
  staticPublishPath: build
  rootDir: react-app

